include("${CMAKE_CURRENT_LIST_DIR}/../cmake/AgoraRtcExtensionCommon.cmake")

file(GLOB AGORA_RTC_IOS_XCFRAMEWORKS
    ${AGORA_RTC_EXTENSION_ROOT}/ios/libs/*.xcframework
)

set(AGORA_RTC_IOS_FRAMEWORKS)
set(AGORA_RTC_IOS_XCFRAMEWORK_PATHS)
set(AGORA_RTC_IOS_DEVICE_FRAMEWORK_SEARCH_PATHS)
set(AGORA_RTC_IOS_SIMULATOR_FRAMEWORK_SEARCH_PATHS)

foreach(AGORA_RTC_IOS_XCFRAMEWORK ${AGORA_RTC_IOS_XCFRAMEWORKS})
    get_filename_component(AGORA_RTC_IOS_FRAMEWORK_NAME ${AGORA_RTC_IOS_XCFRAMEWORK} NAME_WE)

    list(APPEND AGORA_RTC_IOS_FRAMEWORKS
        "-framework ${AGORA_RTC_IOS_FRAMEWORK_NAME}"
    )
    list(APPEND AGORA_RTC_IOS_XCFRAMEWORK_PATHS
        "${AGORA_RTC_IOS_XCFRAMEWORK}"
    )

    if(EXISTS "${AGORA_RTC_IOS_XCFRAMEWORK}/ios-arm64")
        list(APPEND AGORA_RTC_IOS_DEVICE_FRAMEWORK_SEARCH_PATHS
            "${AGORA_RTC_IOS_XCFRAMEWORK}/ios-arm64"
        )
    endif()

    if(EXISTS "${AGORA_RTC_IOS_XCFRAMEWORK}/ios-arm64_x86_64-simulator")
        list(APPEND AGORA_RTC_IOS_SIMULATOR_FRAMEWORK_SEARCH_PATHS
            "${AGORA_RTC_IOS_XCFRAMEWORK}/ios-arm64_x86_64-simulator"
        )
    endif()
endforeach()

list(JOIN AGORA_RTC_IOS_DEVICE_FRAMEWORK_SEARCH_PATHS " " AGORA_RTC_IOS_DEVICE_FRAMEWORK_SEARCH_PATHS_STRING)
list(JOIN AGORA_RTC_IOS_SIMULATOR_FRAMEWORK_SEARCH_PATHS " " AGORA_RTC_IOS_SIMULATOR_FRAMEWORK_SEARCH_PATHS_STRING)

agora_rtc_extension_add_library(
    PLATFORM ios
    SDK_INCLUDE_DIR ${AGORA_RTC_EXTENSION_ROOT}/ios/include/rtc
    AOSL_HEADERS_DIR ${AGORA_RTC_EXTENSION_ROOT}/ios/libs/aosl.xcframework/ios-arm64/aosl.framework/Headers
    FRAMEWORKS ${AGORA_RTC_IOS_FRAMEWORKS}
)

if(CMAKE_GENERATOR STREQUAL "Xcode")
    set(CMAKE_XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]
        "$(inherited) ${AGORA_RTC_IOS_DEVICE_FRAMEWORK_SEARCH_PATHS_STRING}"
    )
    set(CMAKE_XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]
        "$(inherited) ${AGORA_RTC_IOS_SIMULATOR_FRAMEWORK_SEARCH_PATHS_STRING}"
    )

    set_target_properties(AgoraRtcExtension PROPERTIES
        XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]
            "$(inherited) ${AGORA_RTC_IOS_DEVICE_FRAMEWORK_SEARCH_PATHS_STRING}"
        XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]
            "$(inherited) ${AGORA_RTC_IOS_SIMULATOR_FRAMEWORK_SEARCH_PATHS_STRING}"
    )
endif()

function(agora_rtc_extension_embed_ios_frameworks TARGET_NAME)
    if(NOT CMAKE_GENERATOR STREQUAL "Xcode")
        return()
    endif()

    if(NOT TARGET ${TARGET_NAME})
        return()
    endif()

    set_target_properties(${TARGET_NAME} PROPERTIES
        XCODE_EMBED_FRAMEWORKS "${AGORA_RTC_IOS_XCFRAMEWORK_PATHS}"
        XCODE_EMBED_FRAMEWORKS_CODE_SIGN_ON_COPY YES
        XCODE_EMBED_FRAMEWORKS_REMOVE_HEADERS_ON_COPY YES
        XCODE_ATTRIBUTE_LD_RUNPATH_SEARCH_PATHS "$(inherited) @executable_path/Frameworks"
    )
endfunction()

if(CMAKE_GENERATOR STREQUAL "Xcode")
    if(DEFINED CC_EXECUTABLE_NAME)
        set(AGORA_RTC_IOS_APP_TARGET ${CC_EXECUTABLE_NAME})
    elseif(DEFINED APP_NAME)
        set(AGORA_RTC_IOS_APP_TARGET "${APP_NAME}-mobile")
    endif()

    if(AGORA_RTC_IOS_APP_TARGET)
        cmake_language(DEFER
            DIRECTORY ${CMAKE_SOURCE_DIR}
            CALL agora_rtc_extension_embed_ios_frameworks ${AGORA_RTC_IOS_APP_TARGET}
        )
    endif()
endif()
