#pragma once

#include <type_traits>
#include <vector>

#include "AgoraBase.h"
#include "AgoraExtensionVersion.h"
#include "AgoraExtensions.h"
#include "AgoraMediaBase.h"
#include "AgoraMediaPlayerTypes.h"
#include "IAgoraFileUploader.h"
#include "IAgoraLog.h"
#include "IAgoraMediaStreamingSource.h"
#include "IAgoraMusicContentCenter.h"
#include "IAgoraRhythmPlayer.h"
#include "IAgoraRtcEngine.h"
#include "IAgoraRtcEngineEx.h"
#include "IAgoraService.h"
#include "IAgoraSpatialAudio.h"
#include "NGIAgoraAudioDeviceManager.h"
#include "NGIAgoraAudioTrack.h"
#include "NGIAgoraDataChannel.h"
#include "NGIAgoraExtensionControl.h"
#include "NGIAgoraExtensionProvider.h"
#include "NGIAgoraLocalUser.h"
#include "NGIAgoraMediaNode.h"
#include "NGIAgoraRtcConnection.h"
#include "NGIAgoraRtmpConnection.h"
#include "NGIAgoraSyncClient.h"
#include "NGIAgoraVideoFrame.h"
#include "NGIAgoraVideoMixerSource.h"
#include "NGIAgoraVideoTrack.h"
#include "bindings/jswrapper/SeApi.h"
#include "bindings/manual/jsb_conversions_spec.h"

// Forward declarations for Agora SDK struct -> se::Value converters.
// Generated by scripts/generate-native-tosevalue.js.

template <typename T, typename std::enable_if<std::is_enum<T>::value, int>::type = 0>
bool nativevalue_to_se(T from, se::Value &to, se::Object *ctx) {
    return nativevalue_to_se(static_cast<int32_t>(from), to, ctx);
}

template <typename T> bool nativevalue_to_se(const agora::Optional<T> &from, se::Value &to, se::Object *ctx) {
    if (!from.has_value()) {
        to.setNull();
        return true;
    }
    return nativevalue_to_se(from.value(), to, ctx);
}

inline bool nativevalue_to_se(const agora::util::AString &from, se::Value &to, se::Object *ctx) {
    return nativevalue_to_se(from ? from->c_str() : "", to, ctx);
}

// ─────────────────────────────────────────────────────────────────────────────
// This file is AUTO-GENERATED by scripts/generate-native-tosevalue.js.
//
// To prevent a specific function from being overwritten on regeneration, add
// the line below immediately above it:
//
//   // do not gen code cover it
//   bool nativevalue_to_se(const YourStruct &from, se::Value &to, se::Object *ctx) { ... }
//
// To add custom code that survives regeneration, write it inside the block:
//
//   // USER CODE BLOCK START
//   // your custom declarations here
//   // USER CODE BLOCK END
// ─────────────────────────────────────────────────────────────────────────────

// AUTO-GENERATED DECLARATIONS START

bool nativevalue_to_se(const agora::base::AgoraServiceConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::base::SyncConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::commons::LogConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::AudioSpectrumData &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::AudioEncodedFrameInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::CacheStatistics &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::ColorSpace &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::ExternalVideoFrame &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::Hdr10MetadataInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::MediaSource &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::PacketOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::PlayerPlaybackStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::PlayerStreamInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::PlayerUpdatedInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::SrcInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::base::VideoFrame &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::ContentInspectModule &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::RecorderInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::SnapshotConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::media::UserAudioSpectrumInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AdvancedConfigInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AdvanceOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AudioEncodedFrameObserverConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AudioParameters &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AudioPcmDataInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AudioRecordingConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AudioTrackConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::AudioVolumeInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::BeautyOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ChannelMediaInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ChannelMediaRelayConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ClientRoleOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::CodecCapInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::CodecCapLevels &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ColorEnhanceOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::DataStreamConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::DeviceInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::DirectCdnStreamingStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::DownlinkNetworkInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::EchoTestConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::EncodedAudioFrameAdvancedSettings &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::EncodedAudioFrameInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::EncodedVideoFrameInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::EncryptionConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ExtensionContext &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ExtensionInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::FaceShapeAreaOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::FaceShapeBeautyOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::FilterEffectOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::FocalLengthInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::InjectStreamConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LastmileProbeConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LastmileProbeOneWayResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LastmileProbeResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LeaveChannelOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LiveStreamAdvancedFeature &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LiveTranscoding &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LocalAccessPointConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LocalAudioMixerConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LocalAudioStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LocalTranscoderConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LogUploadServerInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LowlightEnhanceOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::MixedAudioStream &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::MultipathStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::PathStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::PublisherConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::RecorderStreamInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::Rectangle &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::RemoteVideoStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::RtcConnection &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::RtcEngineContext &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::RtcStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ScreenAudioParameters &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ScreenCaptureParameters &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::SegmentationProperty &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::SenderOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::SimulcastStreamConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::SIZE &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::TranscodingUser &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::TranscodingVideoStream &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::UplinkNetworkInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::UserInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoCanvas &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoDenoiserOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoDimensions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoEncoderConfiguration &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoFormat &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoRenderingTracingInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoSubscriptionOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VideoTrackInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::VirtualBackgroundSource &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::WatermarkBuffer &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::WatermarkConfig &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::WatermarkLiteral &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::WatermarkOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::WatermarkRatio &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::WatermarkTimestamp &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::SpatialAudioParams &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::UserInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::VideoLayout &from, se::Value &to, se::Object *ctx);
// USER CODE BLOCK START
bool nativevalue_to_se(const agora::rtc::ChannelMediaOptions &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ThumbImageBuffer &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::ScreenCaptureSourceInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::LocalVideoStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::RemoteAudioStats &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const std::vector<agora::VideoLayout> &from, se::Value &to, se::Object *ctx);

// ── nativevalue_to_se overloads for bridge result structs ──────────────────
// These must be in the header (not anonymous namespace) so both the auto-generated
// and manual binding translation units can see them.
#include "agora/AudioDeviceManagerBridge.h"
#include "agora/VideoDeviceManagerBridge.h"
#include "agora/MusicContentCenterBridge.h"
#include "agora/ScreenCaptureSourceListBridge.h"

// Bridge result struct nativevalue_to_se overloads (global namespace)
bool nativevalue_to_se(const GetPlaybackDeviceResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetPlaybackDeviceInfoResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetPlaybackDeviceInfoExResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetPlaybackDeviceVolumeResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetPlaybackDeviceMuteResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetRecordingDeviceResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetRecordingDeviceInfoResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetRecordingDeviceInfoExResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetRecordingDeviceVolumeResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetRecordingDeviceMuteResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetLoopbackDeviceResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetVideoDeviceResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetCachesResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const MCCRequestResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const GetInternalSongCodeResult &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const agora::rtc::MusicCacheInfo &from, se::Value &to, se::Object *ctx);
bool nativevalue_to_se(const std::vector<agora::rtc::MusicCacheInfo> &from, se::Value &to, se::Object *ctx);
// USER CODE BLOCK END
// AUTO-GENERATED DECLARATIONS END
