// clang-format off
/****************************************************************************
 Copyright (c) 2022-2023 Xiamen Yaji Software Co., Ltd.

 http://www.cocos.com

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
****************************************************************************/

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#elif defined(__GNUC__) || defined(__GNUG__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#elif defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable : 4101)
#endif

#include <cassert>
#include "jsb_agora_rtc_ext.h"
#include "bindings/manual/jsb_conversions.h"
#include "bindings/manual/jsb_global.h"

// include agora rtc sdk headers
#include "IAgoraRtcEngine.h"
#include "IAgoraRtcEngineEx.h"
#include "AgoraBase.h"

// AUTO-GENERATED IMPLEMENTATIONS START

// ─────────────────────────────────────────────────────────────────────────────
// This file is AUTO-GENERATED by scripts/generate-sevalue-to-native.js.
//
// To prevent a specific function from being overwritten on regeneration, add
// the line below immediately above it:
//
//   // do not gen code cover it
//   bool sevalue_to_native(const se::Value &from, YourStruct *to, se::Object *ctx) { ... }
//
// Custom code between // USER CODE BLOCK START and // USER CODE BLOCK END is preserved.
// ─────────────────────────────────────────────────────────────────────────────
bool sevalue_to_native(const se::Value &from, agora::UserInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("userId", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->userId), ctx);
    }

    json->getProperty("hasAudio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->hasAudio), ctx);
    }

    json->getProperty("hasVideo", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->hasVideo), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDimensions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::SenderOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("ccMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->ccMode), ctx);
    }

    json->getProperty("codecType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecType), ctx);
    }

    json->getProperty("targetBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->targetBitrate), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedAudioFrameAdvancedSettings *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("speech", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->speech), ctx);
    }

    json->getProperty("sendEvenIfEmpty", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sendEvenIfEmpty), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedAudioFrameInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("codec", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codec), ctx);
    }

    json->getProperty("sampleRateHz", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sampleRateHz), ctx);
    }

    json->getProperty("samplesPerChannel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->samplesPerChannel), ctx);
    }

    json->getProperty("numberOfChannels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->numberOfChannels), ctx);
    }

    json->getProperty("advancedSettings", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->advancedSettings), ctx);
    }

    json->getProperty("captureTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->captureTimeMs), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AudioPcmDataInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("samplesPerChannel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->samplesPerChannel), ctx);
    }

    json->getProperty("channelNum", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->channelNum), ctx);
    }

    json->getProperty("samplesOut", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->samplesOut), ctx);
    }

    json->getProperty("elapsedTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->elapsedTimeMs), ctx);
    }

    json->getProperty("ntpTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->ntpTimeMs), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoSubscriptionOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("type", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->type), ctx);
    }

    json->getProperty("encodedFrameOnly", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encodedFrameOnly), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedVideoFrameInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("codecType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecType), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("framesPerSecond", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->framesPerSecond), ctx);
    }

    json->getProperty("frameType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->frameType), ctx);
    }

    json->getProperty("rotation", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rotation), ctx);
    }

    json->getProperty("trackId", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->trackId), ctx);
    }

    json->getProperty("captureTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->captureTimeMs), ctx);
    }

    json->getProperty("decodeTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->decodeTimeMs), ctx);
    }

    json->getProperty("streamType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->streamType), ctx);
    }

    json->getProperty("presentationMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->presentationMs), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AdvanceOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("encodingPreference", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encodingPreference), ctx);
    }

    json->getProperty("compressionPreference", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->compressionPreference), ctx);
    }

    json->getProperty("encodeAlpha", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encodeAlpha), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::CodecCapLevels *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("hwDecodingLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->hwDecodingLevel), ctx);
    }

    json->getProperty("swDecodingLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->swDecodingLevel), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::CodecCapInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("codecType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecType), ctx);
    }

    json->getProperty("codecCapMask", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecCapMask), ctx);
    }

    json->getProperty("codecLevels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecLevels), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::FocalLengthInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("cameraDirection", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->cameraDirection), ctx);
    }

    json->getProperty("focalLengthType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->focalLengthType), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoEncoderConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("codecType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecType), ctx);
    }

    json->getProperty("dimensions", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->dimensions), ctx);
    }

    json->getProperty("frameRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->frameRate), ctx);
    }

    json->getProperty("bitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->bitrate), ctx);
    }

    json->getProperty("minBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->minBitrate), ctx);
    }

    json->getProperty("orientationMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->orientationMode), ctx);
    }

    json->getProperty("degradationPreference", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->degradationPreference), ctx);
    }

    json->getProperty("mirrorMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mirrorMode), ctx);
    }

    json->getProperty("advanceOptions", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->advanceOptions), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::DataStreamConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("syncWithAudio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->syncWithAudio), ctx);
    }

    json->getProperty("ordered", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->ordered), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastStreamConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("dimensions", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->dimensions), ctx);
    }

    json->getProperty("kBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->kBitrate), ctx);
    }

    json->getProperty("framerate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->framerate), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::Rectangle *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("x", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->x), ctx);
    }

    json->getProperty("y", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->y), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkRatio *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("xRatio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->xRatio), ctx);
    }

    json->getProperty("yRatio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->yRatio), ctx);
    }

    json->getProperty("widthRatio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->widthRatio), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("visibleInPreview", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->visibleInPreview), ctx);
    }

    json->getProperty("positionInLandscapeMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->positionInLandscapeMode), ctx);
    }

    json->getProperty("positionInPortraitMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->positionInPortraitMode), ctx);
    }

    json->getProperty("watermarkRatio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->watermarkRatio), ctx);
    }

    json->getProperty("mode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mode), ctx);
    }

    json->getProperty("zOrder", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->zOrder), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkTimestamp *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("fontSize", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->fontSize), ctx);
    }

    json->getProperty("strokeWidth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->strokeWidth), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkLiteral *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("fontSize", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->fontSize), ctx);
    }

    json->getProperty("strokeWidth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->strokeWidth), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkBuffer *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("length", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->length), ctx);
    }

    json->getProperty("format", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->format), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("type", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->type), ctx);
    }

    json->getProperty("options", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->options), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::PathStats *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("type", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->type), ctx);
    }

    json->getProperty("txKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txKBitRate), ctx);
    }

    json->getProperty("rxKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxKBitRate), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::MultipathStats *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("lanTxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lanTxBytes), ctx);
    }

    json->getProperty("lanRxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lanRxBytes), ctx);
    }

    json->getProperty("wifiTxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->wifiTxBytes), ctx);
    }

    json->getProperty("wifiRxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->wifiRxBytes), ctx);
    }

    json->getProperty("mobileTxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mobileTxBytes), ctx);
    }

    json->getProperty("mobileRxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mobileRxBytes), ctx);
    }

    json->getProperty("activePathNum", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->activePathNum), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::RtcStats *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("duration", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->duration), ctx);
    }

    json->getProperty("txBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txBytes), ctx);
    }

    json->getProperty("rxBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxBytes), ctx);
    }

    json->getProperty("txAudioBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txAudioBytes), ctx);
    }

    json->getProperty("txVideoBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txVideoBytes), ctx);
    }

    json->getProperty("rxAudioBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxAudioBytes), ctx);
    }

    json->getProperty("rxVideoBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxVideoBytes), ctx);
    }

    json->getProperty("txKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txKBitRate), ctx);
    }

    json->getProperty("rxKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxKBitRate), ctx);
    }

    json->getProperty("rxAudioKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxAudioKBitRate), ctx);
    }

    json->getProperty("txAudioKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txAudioKBitRate), ctx);
    }

    json->getProperty("rxVideoKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxVideoKBitRate), ctx);
    }

    json->getProperty("txVideoKBitRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txVideoKBitRate), ctx);
    }

    json->getProperty("lastmileDelay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lastmileDelay), ctx);
    }

    json->getProperty("userCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->userCount), ctx);
    }

    json->getProperty("cpuAppUsage", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->cpuAppUsage), ctx);
    }

    json->getProperty("cpuTotalUsage", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->cpuTotalUsage), ctx);
    }

    json->getProperty("gatewayRtt", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->gatewayRtt), ctx);
    }

    json->getProperty("memoryAppUsageRatio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->memoryAppUsageRatio), ctx);
    }

    json->getProperty("memoryTotalUsageRatio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->memoryTotalUsageRatio), ctx);
    }

    json->getProperty("memoryAppUsageInKbytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->memoryAppUsageInKbytes), ctx);
    }

    json->getProperty("connectTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->connectTimeMs), ctx);
    }

    json->getProperty("firstAudioPacketDuration", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstAudioPacketDuration), ctx);
    }

    json->getProperty("firstVideoPacketDuration", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstVideoPacketDuration), ctx);
    }

    json->getProperty("firstVideoKeyFramePacketDuration", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstVideoKeyFramePacketDuration), ctx);
    }

    json->getProperty("packetsBeforeFirstKeyFramePacket", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->packetsBeforeFirstKeyFramePacket), ctx);
    }

    json->getProperty("firstAudioPacketDurationAfterUnmute", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstAudioPacketDurationAfterUnmute), ctx);
    }

    json->getProperty("firstVideoPacketDurationAfterUnmute", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstVideoPacketDurationAfterUnmute), ctx);
    }

    json->getProperty("firstVideoKeyFramePacketDurationAfterUnmute", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstVideoKeyFramePacketDurationAfterUnmute), ctx);
    }

    json->getProperty("firstVideoKeyFrameDecodedDurationAfterUnmute", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstVideoKeyFrameDecodedDurationAfterUnmute), ctx);
    }

    json->getProperty("firstVideoKeyFrameRenderedDurationAfterUnmute", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->firstVideoKeyFrameRenderedDurationAfterUnmute), ctx);
    }

    json->getProperty("txPacketLossRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txPacketLossRate), ctx);
    }

    json->getProperty("rxPacketLossRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxPacketLossRate), ctx);
    }

    json->getProperty("lanAccelerateState", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lanAccelerateState), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ClientRoleOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("audienceLatencyLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audienceLatencyLevel), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoFormat *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("fps", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->fps), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoTrackInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("isLocal", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->isLocal), ctx);
    }

    json->getProperty("ownerUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->ownerUid), ctx);
    }

    json->getProperty("trackId", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->trackId), ctx);
    }

    json->getProperty("codecType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->codecType), ctx);
    }

    json->getProperty("encodedFrameOnly", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encodedFrameOnly), ctx);
    }

    json->getProperty("sourceType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sourceType), ctx);
    }

    json->getProperty("observationPosition", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->observationPosition), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AudioVolumeInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("volume", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->volume), ctx);
    }

    json->getProperty("vad", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->vad), ctx);
    }

    json->getProperty("voicePitch", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->voicePitch), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::DeviceInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("isLowLatencyAudioSupported", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->isLowLatencyAudioSupported), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioStats *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("numChannels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->numChannels), ctx);
    }

    json->getProperty("sentSampleRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sentSampleRate), ctx);
    }

    json->getProperty("sentBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sentBitrate), ctx);
    }

    json->getProperty("internalCodec", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->internalCodec), ctx);
    }

    json->getProperty("txPacketLossRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->txPacketLossRate), ctx);
    }

    json->getProperty("audioDeviceDelay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioDeviceDelay), ctx);
    }

    json->getProperty("audioPlayoutDelay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioPlayoutDelay), ctx);
    }

    json->getProperty("earMonitorDelay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->earMonitorDelay), ctx);
    }

    json->getProperty("aecEstimatedDelay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->aecEstimatedDelay), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LiveStreamAdvancedFeature *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("opened", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->opened), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::TranscodingUser *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("x", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->x), ctx);
    }

    json->getProperty("y", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->y), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("zOrder", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->zOrder), ctx);
    }

    json->getProperty("alpha", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->alpha), ctx);
    }

    json->getProperty("audioChannel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioChannel), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LiveTranscoding *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("videoBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoBitrate), ctx);
    }

    json->getProperty("videoFramerate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoFramerate), ctx);
    }

    json->getProperty("lowLatency", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lowLatency), ctx);
    }

    json->getProperty("videoGop", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoGop), ctx);
    }

    json->getProperty("videoCodecProfile", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoCodecProfile), ctx);
    }

    json->getProperty("backgroundColor", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->backgroundColor), ctx);
    }

    json->getProperty("videoCodecType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoCodecType), ctx);
    }

    json->getProperty("userCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->userCount), ctx);
    }

    json->getProperty("watermarkCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->watermarkCount), ctx);
    }

    json->getProperty("backgroundImageCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->backgroundImageCount), ctx);
    }

    json->getProperty("audioSampleRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioSampleRate), ctx);
    }

    json->getProperty("audioBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioBitrate), ctx);
    }

    json->getProperty("audioChannels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioChannels), ctx);
    }

    json->getProperty("audioCodecProfile", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioCodecProfile), ctx);
    }

    json->getProperty("advancedFeatureCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->advancedFeatureCount), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::TranscodingVideoStream *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("sourceType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sourceType), ctx);
    }

    json->getProperty("remoteUserUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->remoteUserUid), ctx);
    }

    json->getProperty("mediaPlayerId", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mediaPlayerId), ctx);
    }

    json->getProperty("x", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->x), ctx);
    }

    json->getProperty("y", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->y), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("zOrder", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->zOrder), ctx);
    }

    json->getProperty("alpha", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->alpha), ctx);
    }

    json->getProperty("mirror", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mirror), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LocalTranscoderConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("streamCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->streamCount), ctx);
    }

    json->getProperty("videoOutputConfiguration", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoOutputConfiguration), ctx);
    }

    json->getProperty("syncWithPrimaryCamera", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->syncWithPrimaryCamera), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::MixedAudioStream *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("sourceType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sourceType), ctx);
    }

    json->getProperty("remoteUserUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->remoteUserUid), ctx);
    }

    json->getProperty("trackId", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->trackId), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioMixerConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("streamCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->streamCount), ctx);
    }

    json->getProperty("syncWithLocalMic", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->syncWithLocalMic), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("probeUplink", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->probeUplink), ctx);
    }

    json->getProperty("probeDownlink", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->probeDownlink), ctx);
    }

    json->getProperty("expectedUplinkBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->expectedUplinkBitrate), ctx);
    }

    json->getProperty("expectedDownlinkBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->expectedDownlinkBitrate), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeOneWayResult *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("packetLossRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->packetLossRate), ctx);
    }

    json->getProperty("jitter", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->jitter), ctx);
    }

    json->getProperty("availableBandwidth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->availableBandwidth), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeResult *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("state", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->state), ctx);
    }

    json->getProperty("uplinkReport", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uplinkReport), ctx);
    }

    json->getProperty("downlinkReport", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->downlinkReport), ctx);
    }

    json->getProperty("rtt", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rtt), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoCanvas *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("subviewUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->subviewUid), ctx);
    }

    json->getProperty("view", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->view), ctx);
    }

    json->getProperty("backgroundColor", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->backgroundColor), ctx);
    }

    json->getProperty("renderMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->renderMode), ctx);
    }

    json->getProperty("mirrorMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mirrorMode), ctx);
    }

    json->getProperty("setupMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->setupMode), ctx);
    }

    json->getProperty("sourceType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sourceType), ctx);
    }

    json->getProperty("mediaPlayerId", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mediaPlayerId), ctx);
    }

    json->getProperty("cropArea", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->cropArea), ctx);
    }

    json->getProperty("enableAlphaMask", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enableAlphaMask), ctx);
    }

    json->getProperty("position", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->position), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::BeautyOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("lighteningContrastLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lighteningContrastLevel), ctx);
    }

    json->getProperty("lighteningLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lighteningLevel), ctx);
    }

    json->getProperty("smoothnessLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->smoothnessLevel), ctx);
    }

    json->getProperty("rednessLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rednessLevel), ctx);
    }

    json->getProperty("sharpnessLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sharpnessLevel), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::FaceShapeAreaOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("shapeArea", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->shapeArea), ctx);
    }

    json->getProperty("shapeIntensity", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->shapeIntensity), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::FaceShapeBeautyOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("shapeStyle", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->shapeStyle), ctx);
    }

    json->getProperty("styleIntensity", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->styleIntensity), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::FilterEffectOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("strength", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->strength), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LowlightEnhanceOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("mode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mode), ctx);
    }

    json->getProperty("level", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->level), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDenoiserOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("mode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mode), ctx);
    }

    json->getProperty("level", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->level), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ColorEnhanceOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("strengthLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->strengthLevel), ctx);
    }

    json->getProperty("skinProtectLevel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->skinProtectLevel), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VirtualBackgroundSource *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("background_source_type", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->background_source_type), ctx);
    }

    json->getProperty("color", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->color), ctx);
    }

    json->getProperty("blur_degree", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->blur_degree), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::SegmentationProperty *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("modelType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->modelType), ctx);
    }

    json->getProperty("greenCapacity", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->greenCapacity), ctx);
    }

    json->getProperty("screenColorType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->screenColorType), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AudioTrackConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("enableLocalPlayback", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enableLocalPlayback), ctx);
    }

    json->getProperty("enableAudioProcessing", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enableAudioProcessing), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenAudioParameters *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("sampleRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sampleRate), ctx);
    }

    json->getProperty("channels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->channels), ctx);
    }

    json->getProperty("captureSignalVolume", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->captureSignalVolume), ctx);
    }

    json->getProperty("excludeCurrentProcessAudio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->excludeCurrentProcessAudio), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureParameters *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("captureAudio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->captureAudio), ctx);
    }

    json->getProperty("audioParams", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioParams), ctx);
    }

    json->getProperty("dimensions", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->dimensions), ctx);
    }

    json->getProperty("frameRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->frameRate), ctx);
    }

    json->getProperty("bitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->bitrate), ctx);
    }

    json->getProperty("captureMouseCursor", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->captureMouseCursor), ctx);
    }

    json->getProperty("windowFocus", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->windowFocus), ctx);
    }

    json->getProperty("excludeWindowCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->excludeWindowCount), ctx);
    }

    json->getProperty("highLightWidth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->highLightWidth), ctx);
    }

    json->getProperty("highLightColor", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->highLightColor), ctx);
    }

    json->getProperty("enableHighLight", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enableHighLight), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AudioRecordingConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("encode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encode), ctx);
    }

    json->getProperty("sampleRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sampleRate), ctx);
    }

    json->getProperty("fileRecordingType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->fileRecordingType), ctx);
    }

    json->getProperty("quality", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->quality), ctx);
    }

    json->getProperty("recordingChannel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->recordingChannel), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AudioEncodedFrameObserverConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("postionType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->postionType), ctx);
    }

    json->getProperty("encodingType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encodingType), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaRelayConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("destCount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->destCount), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::UplinkNetworkInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("video_encoder_target_bitrate_bps", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->video_encoder_target_bitrate_bps), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::DownlinkNetworkInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("lastmile_buffer_delay_time_ms", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lastmile_buffer_delay_time_ms), ctx);
    }

    json->getProperty("bandwidth_estimation_bps", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->bandwidth_estimation_bps), ctx);
    }

    json->getProperty("total_downscale_level_count", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->total_downscale_level_count), ctx);
    }

    json->getProperty("total_received_video_count", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->total_received_video_count), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::EncryptionConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("encryptionMode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encryptionMode), ctx);
    }

    json->getProperty("encryptionKdfSalt", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->encryptionKdfSalt), ctx);
    }

    json->getProperty("datastreamEncryptionEnabled", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->datastreamEncryptionEnabled), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::EchoTestConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("view", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->view), ctx);
    }

    json->getProperty("enableAudio", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enableAudio), ctx);
    }

    json->getProperty("enableVideo", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enableVideo), ctx);
    }

    json->getProperty("intervalInSeconds", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->intervalInSeconds), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::UserInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("userAccount", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->userAccount), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::VideoRenderingTracingInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("elapsedTime", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->elapsedTime), ctx);
    }

    json->getProperty("start2JoinChannel", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->start2JoinChannel), ctx);
    }

    json->getProperty("join2JoinSuccess", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->join2JoinSuccess), ctx);
    }

    json->getProperty("joinSuccess2RemoteJoined", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->joinSuccess2RemoteJoined), ctx);
    }

    json->getProperty("remoteJoined2SetView", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->remoteJoined2SetView), ctx);
    }

    json->getProperty("remoteJoined2UnmuteVideo", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->remoteJoined2UnmuteVideo), ctx);
    }

    json->getProperty("remoteJoined2PacketReceived", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->remoteJoined2PacketReceived), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LogUploadServerInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("serverPort", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->serverPort), ctx);
    }

    json->getProperty("serverHttps", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->serverHttps), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AdvancedConfigInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("logUploadServer", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->logUploadServer), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAccessPointConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("ipListSize", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->ipListSize), ctx);
    }

    json->getProperty("domainListSize", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->domainListSize), ctx);
    }

    json->getProperty("mode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mode), ctx);
    }

    json->getProperty("advancedConfig", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->advancedConfig), ctx);
    }

    json->getProperty("disableAut", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->disableAut), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::RecorderStreamInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("type", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->type), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::SpatialAudioParams *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("speaker_azimuth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->speaker_azimuth), ctx);
    }

    json->getProperty("speaker_elevation", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->speaker_elevation), ctx);
    }

    json->getProperty("speaker_distance", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->speaker_distance), ctx);
    }

    json->getProperty("speaker_orientation", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->speaker_orientation), ctx);
    }

    json->getProperty("enable_blur", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enable_blur), ctx);
    }

    json->getProperty("enable_air_absorb", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enable_air_absorb), ctx);
    }

    json->getProperty("speaker_attenuation", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->speaker_attenuation), ctx);
    }

    json->getProperty("enable_doppler", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->enable_doppler), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::VideoLayout *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("strUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->strUid), ctx);
    }

    json->getProperty("x", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->x), ctx);
    }

    json->getProperty("y", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->y), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("videoState", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoState), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionContext *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("isValid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->isValid), ctx);
    }

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::AudioParameters *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("sample_rate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->sample_rate), ctx);
    }

    json->getProperty("channels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->channels), ctx);
    }

    json->getProperty("frames_per_buffer", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->frames_per_buffer), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVideoStats *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("uid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->uid), ctx);
    }

    json->getProperty("delay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->delay), ctx);
    }

    json->getProperty("e2eDelay", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->e2eDelay), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("receivedBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->receivedBitrate), ctx);
    }

    json->getProperty("decoderInputFrameRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->decoderInputFrameRate), ctx);
    }

    json->getProperty("decoderOutputFrameRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->decoderOutputFrameRate), ctx);
    }

    json->getProperty("rendererOutputFrameRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rendererOutputFrameRate), ctx);
    }

    json->getProperty("frameLossRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->frameLossRate), ctx);
    }

    json->getProperty("packetLossRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->packetLossRate), ctx);
    }

    json->getProperty("rxStreamType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxStreamType), ctx);
    }

    json->getProperty("totalFrozenTime", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->totalFrozenTime), ctx);
    }

    json->getProperty("frozenRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->frozenRate), ctx);
    }

    json->getProperty("avSyncTimeMs", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->avSyncTimeMs), ctx);
    }

    json->getProperty("totalActiveTime", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->totalActiveTime), ctx);
    }

    json->getProperty("publishDuration", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->publishDuration), ctx);
    }

    json->getProperty("mosValue", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mosValue), ctx);
    }

    json->getProperty("rxVideoBytes", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->rxVideoBytes), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::InjectStreamConfig *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("videoGop", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoGop), ctx);
    }

    json->getProperty("videoFramerate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoFramerate), ctx);
    }

    json->getProperty("videoBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoBitrate), ctx);
    }

    json->getProperty("audioSampleRate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioSampleRate), ctx);
    }

    json->getProperty("audioBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioBitrate), ctx);
    }

    json->getProperty("audioChannels", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioChannels), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::PublisherConfiguration *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    json->getProperty("framerate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->framerate), ctx);
    }

    json->getProperty("bitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->bitrate), ctx);
    }

    json->getProperty("defaultLayout", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->defaultLayout), ctx);
    }

    json->getProperty("lifecycle", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->lifecycle), ctx);
    }

    json->getProperty("owner", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->owner), ctx);
    }

    json->getProperty("injectStreamWidth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->injectStreamWidth), ctx);
    }

    json->getProperty("injectStreamHeight", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->injectStreamHeight), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::SIZE *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ThumbImageBuffer *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("length", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->length), ctx);
    }

    json->getProperty("width", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->width), ctx);
    }

    json->getProperty("height", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->height), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::LeaveChannelOptions *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("stopAudioMixing", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->stopAudioMixing), ctx);
    }

    json->getProperty("stopAllEffect", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->stopAllEffect), ctx);
    }

    json->getProperty("stopMicrophoneRecording", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->stopMicrophoneRecording), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::RtcEngineContext *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("channelProfile", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->channelProfile), ctx);
    }

    json->getProperty("audioScenario", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioScenario), ctx);
    }

    json->getProperty("areaCode", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->areaCode), ctx);
    }

    json->getProperty("logConfig", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->logConfig), ctx);
    }

    json->getProperty("threadPriority", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->threadPriority), ctx);
    }

    json->getProperty("useExternalEglContext", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->useExternalEglContext), ctx);
    }

    json->getProperty("domainLimit", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->domainLimit), ctx);
    }

    json->getProperty("autoRegisterAgoraExtensions", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->autoRegisterAgoraExtensions), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::DirectCdnStreamingStats *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("videoWidth", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoWidth), ctx);
    }

    json->getProperty("videoHeight", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoHeight), ctx);
    }

    json->getProperty("fps", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->fps), ctx);
    }

    json->getProperty("videoBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->videoBitrate), ctx);
    }

    json->getProperty("audioBitrate", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->audioBitrate), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInfo *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("mediaSourceType", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->mediaSourceType), ctx);
    }

    json->getProperty("remoteUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->remoteUid), ctx);
    }

    json->getProperty("localUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->localUid), ctx);
    }

    return ok;
}

bool sevalue_to_native(const se::Value &from, agora::rtc::RtcConnection *to, se::Object *ctx)
{
    assert(from.isObject());
    se::Object *json = from.toObject();
    se::Value field;
    bool ok = true;

    json->getProperty("localUid", &field, true);
    if (!field.isNullOrUndefined()) {
        ok &= sevalue_to_native(field, &(to->localUid), ctx);
    }

    return ok;
}
// USER CODE BLOCK START
bool sevalue_to_native(const se::Value &from, agora::media::SnapshotConfig *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcImage *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaOptions *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::CameraCapturerConfiguration *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastConfig *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureConfiguration *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::DirectCdnStreamingMediaOptions *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::AgoraRhythmPlayerConfig *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::media::ContentInspectConfig *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvancedAudioOptions *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::ImageTrackOptions *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVoicePositionInfo *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::SpatialAudioZone *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::media::MediaRecorderConfiguration *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::rtc::MusicContentCenterConfiguration *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::util::CopyableAutoPtr<agora::util::IString> *to, se::Object *ctx) { return true; }
bool sevalue_to_native(const se::Value &from, agora::commons::LogConfig *to, se::Object *ctx) { return true; }
// USER CODE BLOCK END
// AUTO-GENERATED IMPLEMENTATIONS END

#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__) || defined(__GNUG__)
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif
