#pragma once

#include "bindings/jswrapper/SeApi.h"
#include "AgoraOptional.h"

// Generic converter for agora::Optional<T> — handles Optional<bool>,
// Optional<int>, Optional<enum> etc. in one shot.
// When the JS value is null/undefined, the Optional is set to nullopt.
template<typename T>
bool sevalue_to_native(const se::Value &from, agora::Optional<T> *to, se::Object *ctx) {
    if (from.isNullOrUndefined()) {
        *to = agora::nullopt;
        return true;
    }
    T val{};
    if (!sevalue_to_native(from, &val, ctx)) return false;
    *to = std::move(val);
    return true;
}

// Forward declarations — sevalue_to_native implementations are
// generated by scripts/generate-sevalue-to-native.js.
// Re-run: npm run genbindings:sevalue

// AUTO-GENERATED DECLARATIONS START

bool sevalue_to_native(const se::Value &from, agora::UserInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDimensions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SenderOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedAudioFrameAdvancedSettings *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedAudioFrameInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioPcmDataInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoSubscriptionOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedVideoFrameInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvanceOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::CodecCapLevels *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::CodecCapInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FocalLengthInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoEncoderConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DataStreamConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastStreamConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::StreamLayerConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Rectangle *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkRatio *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkTimestamp *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkLiteral *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkBuffer *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::PathStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MultipathStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ClientRoleOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoFormat *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoTrackInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioVolumeInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DeviceInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Packet *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LiveStreamAdvancedFeature *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TranscodingUser *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LiveTranscoding *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TranscodingVideoStream *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalTranscoderConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MixedAudioStream *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioMixerConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeOneWayResult *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeResult *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoCanvas *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::BeautyOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FaceShapeAreaOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FaceShapeBeautyOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FilterEffectOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LowlightEnhanceOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDenoiserOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ColorEnhanceOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VirtualBackgroundSource *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SegmentationProperty *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioTrackConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenAudioParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioRecordingConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioEncodedFrameObserverConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaRelayConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::UplinkNetworkInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DownlinkNetworkInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::PeerDownlinkInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncryptionConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EchoTestConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::UserInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenVideoParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureParameters2 *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoRenderingTracingInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LogUploadServerInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvancedConfigInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAccessPointConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RecorderStreamInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::SpatialAudioParams *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::VideoLayout *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionVersion *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion<IExtensionProvider> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion<IExtensionProviderV2> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion<IAudioFilter> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion<IAudioFilterV2> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion<IExtensionVideoFilter> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInterfaceVersion<IScreenCaptureSource> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoEncoderSettings *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDecoderSettings *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionContext *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ImagePayloadData *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::InputSeiData *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MusicCacheInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MvProperty *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ClimaxSegment *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Music *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MusicContentCenterConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AgoraRhythmPlayerConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVideoStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoCompositingLayout *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Region *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::InjectStreamConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::PublisherConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::CameraCapturerConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SIZE *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ThumbImageBuffer *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureSourceInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvancedAudioOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ImageTrackOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LeaveChannelOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcEngineContext *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Metadata *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DirectCdnStreamingStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DirectCdnStreamingMediaOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcConnection *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::DataChannelConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TConnectionInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcConnectionConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtmpConnectionConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioEncoderConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVoicePositionInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SpatialAudioZone *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalSpatialAudioConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioDeviceInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LoopbackRecordingOption *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioSinkWants *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioTrackStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteAudioTrackStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioEncFrameRecvParams *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::DataChannelInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::UserDataChannelInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Capabilities *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionMetaInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionVideoCodecInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalVideoTrackStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVideoTrackStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ANAStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioProcessingStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioDetailedStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioVolumeInformation *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TConnectSettings *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtmpStreamingAudioConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtmpStreamingVideoConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtmpConnectionInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RawPixelBuffer *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::PaddedRawPixelBuffer *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TextureInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoFrameData *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoFrameDataV2 *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AlphaChannel *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MixerLayoutConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::StreamLayerConfigInternal *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastConfigInternal *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastStreamProfile *to, se::Object *ctx);
// AUTO-GENERATED DECLARATIONS END
