#include "jsb_agora_rtc_manual.h"

#include "agora/AudioDeviceCollectionBridge.h"
#include "agora/AudioDeviceManagerBridge.h"
#include "agora/H265TranscoderBridge.h"
#include "agora/LocalSpatialAudioEngineBridge.h"
#include "agora/MediaPlayerBridge.h"
#include "agora/MediaPlayerCacheManagerBridge.h"
#include "agora/MediaRecorderBridge.h"
#include "agora/MusicContentCenterBridge.h"
#include "agora/MusicPlayerBridge.h"
#include "agora/RtcEngineExBridge.h"
#include "agora/ScreenCaptureSourceListBridge.h"
#include "agora/VideoDeviceCollectionBridge.h"
#include "agora/VideoDeviceManagerBridge.h"
#include "agora/VideoEffectObjectBridge.h"
#include "bindings/auto/jsb_agora_rtc_engine_bridge_auto.h"
#include "bindings/manual/jsb_classtype.h"
#include "bindings/manual/jsb_global.h"
#include "bindings/jswrapper/SeApi.h"

namespace {

// ===== Helpers =============================================================

RtcEngineExBridge *getRtcEngineBridge(se::State &s) {
    return static_cast<RtcEngineExBridge *>(s.nativeThisObject());
}

MediaPlayerBridge *getMediaPlayerBridge(se::State &s) {
    return static_cast<MediaPlayerBridge *>(s.nativeThisObject());
}

bool getArrayBufferOrTypedArray(const se::Value &val, uint8_t **outPtr, size_t *outLen) {
    if (!val.isObject()) return false;
    auto *obj = val.toObject();
    if (obj->isArrayBuffer()) return obj->getArrayBufferData(outPtr, outLen);
    if (obj->isTypedArray()) return obj->getTypedArrayData(outPtr, outLen);
    return false;
}

// ===== RtcEngineExBridge manual bindings ====================================
// Only functions listed in %ignore in agora_rtc_engine_bridge.i are here.
// All other methods are auto-generated by SWIG.

static bool js_agora_RtcEngineBridge_initialize(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.empty() || !args[0].isObject()) {
        SE_REPORT_ERROR("initialize expects a context object");
        return false;
    }

    agora::rtc::RtcEngineContext context;
    if (!sevalue_to_native(args[0], &context, s.thisObject())) {
        SE_REPORT_ERROR("initialize failed to convert RtcEngineContext");
        return false;
    }

    se::Object *eventHandler = nullptr;
    se::Value eventHandlerValue;
    auto *ctxObj = args[0].toObject();
    if (ctxObj->getProperty("eventHandler", &eventHandlerValue) && eventHandlerValue.isObject()) {
        eventHandler = eventHandlerValue.toObject();
    }

    auto *bridge = getRtcEngineBridge(s);
    s.rval().setInt32(bridge ? bridge->initialize(context, eventHandler) : -7);
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_initialize)

static bool js_agora_RtcEngineBridge_joinChannel(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 4) {
        SE_REPORT_ERROR("joinChannel expects four arguments");
        return false;
    }

    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }

    std::string token = args[0].isNullOrUndefined() ? "" : args[0].toString();
    std::string channelId = args[1].toString();

    if (args[2].isString()) {
        std::string info = args[2].toString();
        auto uid = static_cast<agora::rtc::uid_t>(args[3].toInt32());
        s.rval().setInt32(bridge->joinChannel(token, channelId, info, uid));
        return true;
    }

    auto uid = static_cast<agora::rtc::uid_t>(args[2].toInt32());
    if (!args[3].isObject()) {
        SE_REPORT_ERROR("joinChannel options must be an object");
        return false;
    }
    agora::rtc::ChannelMediaOptions options;
    if (!sevalue_to_native(args[3], &options, s.thisObject())) {
        SE_REPORT_ERROR("joinChannel failed to convert ChannelMediaOptions");
        return false;
    }
    s.rval().setInt32(bridge->joinChannel(token, channelId, uid, options));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_joinChannel)

static bool js_agora_RtcEngineBridge_release(se::State &s) {
    const auto &args = s.args();
    bool sync = !args.empty() && args[0].toBoolean();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge != nullptr) { bridge->release(sync); }
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_release)

static bool js_agora_RtcEngineBridge_createMediaPlayer(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto mediaPlayer = bridge->createMediaPlayer();
    if (mediaPlayer == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(mediaPlayer, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_createMediaPlayer)

static bool js_agora_RtcEngineBridge_destroyMediaPlayer(se::State &s) {
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    auto *mediaPlayer = static_cast<MediaPlayerBridge *>(args[0].toObject()->getPrivateData());
    s.rval().setInt32(bridge->destroyMediaPlayer(mediaPlayer));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_destroyMediaPlayer)

static bool js_agora_RtcEngineBridge_createMediaRecorder(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.empty()) { s.rval().setNull(); return true; }
    agora::rtc::RecorderStreamInfo info;
    if (!sevalue_to_native(args[0], &info, s.thisObject())) { s.rval().setNull(); return true; }
    auto recorder = bridge->createMediaRecorder(info);
    if (recorder == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(recorder, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_createMediaRecorder)

static bool js_agora_RtcEngineBridge_destroyMediaRecorder(se::State &s) {
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    auto *recorder = static_cast<MediaRecorderBridge *>(args[0].toObject()->getPrivateData());
    s.rval().setInt32(bridge->destroyMediaRecorder(recorder));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_destroyMediaRecorder)

static bool js_agora_RtcEngineBridge_getScreenCaptureSources(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.empty()) { s.rval().setNull(); return true; }
    agora::rtc::SIZE thumbSize;
    if (!sevalue_to_native(args[0], &thumbSize, s.thisObject())) { s.rval().setNull(); return true; }
    agora::rtc::SIZE iconSize;
    if (args.size() > 1 && args[1].isObject()) {
        sevalue_to_native(args[1], &iconSize, s.thisObject());
    }
    bool includeScreen = args.size() > 2 && args[2].toBoolean();
    auto list = bridge->getScreenCaptureSources(thumbSize, iconSize, includeScreen);
    if (list == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(list, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getScreenCaptureSources)

static bool js_agora_RtcEngineBridge_addVideoWatermark(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.empty()) { s.rval().setInt32(-7); return true; }
    agora::rtc::WatermarkConfig configs;
    if (sevalue_to_native(args[0], &configs, s.thisObject())) {
        s.rval().setInt32(bridge->addVideoWatermark(configs));
        return true;
    }
    agora::rtc::RtcImage watermark;
    if (sevalue_to_native(args[0], &watermark, s.thisObject())) {
        s.rval().setInt32(bridge->addVideoWatermark(watermark));
        return true;
    }
    SE_REPORT_ERROR("addVideoWatermark: invalid argument");
    return false;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_addVideoWatermark)

static bool js_agora_RtcEngineBridge_enableExtension(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.size() < 4) { s.rval().setInt32(-7); return true; }
    std::string provider = args[0].toString();
    std::string extension = args[1].toString();
    if (args[2].isObject()) {
        agora::rtc::ExtensionInfo extensionInfo;
        if (!sevalue_to_native(args[2], &extensionInfo, s.thisObject())) { s.rval().setInt32(-2); return true; }
        bool enable = args[3].toBoolean();
        s.rval().setInt32(bridge->enableExtension(provider.c_str(), extension.c_str(), extensionInfo, enable));
    } else {
        bool enable = args[2].toBoolean();
        int type = args[3].toInt32();
        s.rval().setInt32(bridge->enableExtension(provider.c_str(), extension.c_str(), enable, static_cast<agora::media::MEDIA_SOURCE_TYPE>(type)));
    }
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_enableExtension)

static bool js_agora_RtcEngineBridge_getExtensionProperty(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.size() < 4) { s.rval().setInt32(-7); return true; }
    std::string provider = args[0].toString();
    std::string extension = args[1].toString();
    if (args[2].isObject()) {
        agora::rtc::ExtensionInfo extensionInfo;
        if (!sevalue_to_native(args[2], &extensionInfo, s.thisObject())) { s.rval().setInt32(-2); return true; }
        std::string key = args[3].toString();
        auto result = bridge->getExtensionProperty(provider.c_str(), extension.c_str(), extensionInfo, key);
        nativevalue_to_se(result, s.rval(), s.thisObject());
    } else {
        std::string key = args[2].toString();
        int type = args[3].toInt32();
        auto result = bridge->getExtensionProperty(provider.c_str(), extension.c_str(), key, static_cast<agora::media::MEDIA_SOURCE_TYPE>(type));
        nativevalue_to_se(result, s.rval(), s.thisObject());
    }
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getExtensionProperty)

static bool js_agora_RtcEngineBridge_setExtensionProperty(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.size() < 5) { s.rval().setInt32(-7); return true; }
    std::string provider = args[0].toString();
    std::string extension = args[1].toString();
    if (args[2].isObject()) {
        agora::rtc::ExtensionInfo extensionInfo;
        if (!sevalue_to_native(args[2], &extensionInfo, s.thisObject())) { s.rval().setInt32(-2); return true; }
        std::string key = args[3].toString();
        std::string value = args[4].toString();
        s.rval().setInt32(bridge->setExtensionProperty(provider.c_str(), extension.c_str(), extensionInfo, key, value));
    } else {
        std::string key = args[2].toString();
        std::string value = args[3].toString();
        int type = args[4].toInt32();
        s.rval().setInt32(bridge->setExtensionProperty(provider.c_str(), extension.c_str(), key, value, static_cast<agora::media::MEDIA_SOURCE_TYPE>(type)));
    }
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_setExtensionProperty)

static bool js_agora_RtcEngineBridge_takeSnapshot(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.size() < 2) { s.rval().setInt32(-7); return true; }
    auto uid = static_cast<agora::rtc::uid_t>(args[0].toInt32());
    if (args[1].isString()) {
        s.rval().setInt32(bridge->takeSnapshot(uid, args[1].toString()));
    } else {
        agora::media::SnapshotConfig config;
        if (!sevalue_to_native(args[1], &config, s.thisObject())) { s.rval().setInt32(-2); return true; }
        s.rval().setInt32(bridge->takeSnapshot(uid, config));
    }
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_takeSnapshot)

static bool js_agora_RtcEngineBridge_takeSnapshotEx(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.size() < 3) { s.rval().setInt32(-7); return true; }
    agora::rtc::RtcConnection connection;
    if (!sevalue_to_native(args[0], &connection, s.thisObject())) { s.rval().setInt32(-2); return true; }
    auto uid = static_cast<agora::rtc::uid_t>(args[1].toInt32());
    if (args[2].isString()) {
        s.rval().setInt32(bridge->takeSnapshotEx(connection, uid, args[2].toString()));
    } else {
        agora::media::SnapshotConfig config;
        if (!sevalue_to_native(args[2], &config, s.thisObject())) { s.rval().setInt32(-2); return true; }
        s.rval().setInt32(bridge->takeSnapshotEx(connection, uid, config));
    }
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_takeSnapshotEx)

static bool js_agora_RtcEngineBridge_getAudioDeviceManager(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto mgr = bridge->getAudioDeviceManager();
    if (mgr == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(mgr, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getAudioDeviceManager)

static bool js_agora_RtcEngineBridge_getVideoDeviceManager(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto mgr = bridge->getVideoDeviceManager();
    if (mgr == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(mgr, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getVideoDeviceManager)

static bool js_agora_RtcEngineBridge_getMusicContentCenter(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto mcc = bridge->getMusicContentCenter();
    if (mcc == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(mcc, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getMusicContentCenter)

static bool js_agora_RtcEngineBridge_getMediaPlayerCacheManager(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto mgr = bridge->getMediaPlayerCacheManager();
    if (mgr == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(mgr, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getMediaPlayerCacheManager)

static bool js_agora_RtcEngineBridge_getLocalSpatialAudioEngine(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto engine = bridge->getLocalSpatialAudioEngine();
    if (engine == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(engine, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getLocalSpatialAudioEngine)

static bool js_agora_RtcEngineBridge_createVideoEffectObject(se::State &s) {
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.size() < 2) { s.rval().setNull(); return true; }
    std::string bundlePath = args[0].toString();
    int type = args[1].toInt32();
    auto obj = bridge->createVideoEffectObject(bundlePath, static_cast<agora::media::MEDIA_SOURCE_TYPE>(type));
    if (obj == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(obj, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_createVideoEffectObject)

static bool js_agora_RtcEngineBridge_destroyVideoEffectObject(se::State &s) {
    const auto &args = s.args();
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    auto *obj = static_cast<VideoEffectObjectBridge *>(args[0].toObject()->getPrivateData());
    s.rval().setInt32(bridge->destroyVideoEffectObject(obj));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_destroyVideoEffectObject)

static bool js_agora_RtcEngineBridge_getH265Transcoder(se::State &s) {
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setNull(); return true; }
    auto transcoder = bridge->getH265Transcoder();
    if (transcoder == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(transcoder, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_getH265Transcoder)

// ===== MediaPlayerBridge manual bindings ====================================

static bool js_agora_MediaPlayerBridge_registerPlayerSourceObserver(se::State &s) {
    const auto &args = s.args();
    auto *player = getMediaPlayerBridge(s);
    if (player == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    se::Object *observer = args[0].toObject();
    s.rval().setInt32(player->registerPlayerSourceObserver(observer));
    return true;
}
SE_BIND_FUNC(js_agora_MediaPlayerBridge_registerPlayerSourceObserver)

static bool js_agora_MediaPlayerBridge_setPlayerOption(se::State &s) {
    const auto &args = s.args();
    auto *player = getMediaPlayerBridge(s);
    if (player == nullptr || args.size() < 2) { s.rval().setInt32(-2); return true; }
    std::string key = args[0].toString();
    if (args[1].isString()) {
        s.rval().setInt32(player->setPlayerOption(key, args[1].toString()));
    } else {
        s.rval().setInt32(player->setPlayerOption(key, args[1].toInt32()));
    }
    return true;
}
SE_BIND_FUNC(js_agora_MediaPlayerBridge_setPlayerOption)

// ===== MusicContentCenterBridge manual bindings ============================

static bool js_agora_MusicContentCenterBridge_unregisterEventHandler(se::State &s) {
    auto *mcc = static_cast<MusicContentCenterBridge *>(s.nativeThisObject());
    s.rval().setInt32(mcc ? mcc->unregisterEventHandler() : -2);
    return true;
}
SE_BIND_FUNC(js_agora_MusicContentCenterBridge_unregisterEventHandler)

static bool js_agora_MusicContentCenterBridge_createMusicPlayer(se::State &s) {
    auto *mcc = static_cast<MusicContentCenterBridge *>(s.nativeThisObject());
    if (mcc == nullptr) { s.rval().setNull(); return true; }
    auto player = mcc->createMusicPlayer();
    if (player == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(player, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_MusicContentCenterBridge_createMusicPlayer)

static bool js_agora_MusicContentCenterBridge_destroyMusicPlayer(se::State &s) {
    const auto &args = s.args();
    auto *mcc = static_cast<MusicContentCenterBridge *>(s.nativeThisObject());
    if (mcc == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    auto *player = static_cast<MusicPlayerBridge *>(args[0].toObject()->getPrivateData());
    s.rval().setInt32(mcc->destroyMusicPlayer(player));
    return true;
}
SE_BIND_FUNC(js_agora_MusicContentCenterBridge_destroyMusicPlayer)

// ===== H265TranscoderBridge manual bindings ================================

static bool js_agora_H265TranscoderBridge_registerTranscoderObserver(se::State &s) {
    const auto &args = s.args();
    auto *transcoder = static_cast<H265TranscoderBridge *>(s.nativeThisObject());
    if (transcoder == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    se::Object *observer = args[0].toObject();
    s.rval().setInt32(transcoder->registerTranscoderObserver(observer));
    return true;
}
SE_BIND_FUNC(js_agora_H265TranscoderBridge_registerTranscoderObserver)

// ===== MediaRecorderBridge manual bindings ================================

static bool js_agora_MediaRecorderBridge_setMediaRecorderObserver(se::State &s) {
    const auto &args = s.args();
    auto *recorder = static_cast<MediaRecorderBridge *>(s.nativeThisObject());
    if (recorder == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    se::Object *observer = args[0].toObject();
    s.rval().setInt32(recorder->setMediaRecorderObserver(observer));
    return true;
}
SE_BIND_FUNC(js_agora_MediaRecorderBridge_setMediaRecorderObserver)

// ===== AudioDeviceCollectionBridge merged bindings ========================

static bool js_agora_AudioDeviceCollectionBridge_getDevice(se::State &s) {
    const auto &args = s.args();
    auto *collection = static_cast<AudioDeviceCollectionBridge *>(s.nativeThisObject());
    if (collection == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    int index = args[0].toInt32();
    auto exResult = collection->getDeviceEx(index);
    if (exResult.errorCode == 0) {
        nativevalue_to_se(exResult, s.rval(), s.thisObject());
    } else {
        nativevalue_to_se(collection->getDevice(index), s.rval(), s.thisObject());
    }
    return true;
}
SE_BIND_FUNC(js_agora_AudioDeviceCollectionBridge_getDevice)

static bool js_agora_AudioDeviceCollectionBridge_getDefaultDevice(se::State &s) {
    auto *collection = static_cast<AudioDeviceCollectionBridge *>(s.nativeThisObject());
    if (collection == nullptr) { s.rval().setInt32(-2); return true; }
    auto exResult = collection->getDefaultDeviceEx();
    if (exResult.errorCode == 0) {
        nativevalue_to_se(exResult, s.rval(), s.thisObject());
    } else {
        nativevalue_to_se(collection->getDefaultDevice(), s.rval(), s.thisObject());
    }
    return true;
}
SE_BIND_FUNC(js_agora_AudioDeviceCollectionBridge_getDefaultDevice)

// ===== AudioDeviceManagerBridge manual bindings ===========================

static bool js_agora_AudioDeviceManagerBridge_enumeratePlaybackDevices(se::State &s) {
    auto *mgr = static_cast<AudioDeviceManagerBridge *>(s.nativeThisObject());
    if (mgr == nullptr) { s.rval().setNull(); return true; }
    auto collection = mgr->enumeratePlaybackDevices();
    if (collection == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(collection, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_AudioDeviceManagerBridge_enumeratePlaybackDevices)

static bool js_agora_AudioDeviceManagerBridge_enumerateRecordingDevices(se::State &s) {
    auto *mgr = static_cast<AudioDeviceManagerBridge *>(s.nativeThisObject());
    if (mgr == nullptr) { s.rval().setNull(); return true; }
    auto collection = mgr->enumerateRecordingDevices();
    if (collection == nullptr) { s.rval().setNull(); return true; }
    nativevalue_to_se(collection, s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_AudioDeviceManagerBridge_enumerateRecordingDevices)

static bool js_agora_AudioDeviceManagerBridge_getPlaybackDevice(se::State &s) {
    auto *mgr = static_cast<AudioDeviceManagerBridge *>(s.nativeThisObject());
    if (mgr == nullptr) { s.rval().setInt32(-2); return true; }
    auto exResult = mgr->getPlaybackDeviceInfoEx();
    if (exResult.errorCode == 0) {
        nativevalue_to_se(exResult, s.rval(), s.thisObject());
    } else {
        nativevalue_to_se(mgr->getPlaybackDevice(), s.rval(), s.thisObject());
    }
    return true;
}
SE_BIND_FUNC(js_agora_AudioDeviceManagerBridge_getPlaybackDevice)

static bool js_agora_AudioDeviceManagerBridge_getRecordingDevice(se::State &s) {
    auto *mgr = static_cast<AudioDeviceManagerBridge *>(s.nativeThisObject());
    if (mgr == nullptr) { s.rval().setInt32(-2); return true; }
    auto exResult = mgr->getRecordingDeviceInfoEx();
    if (exResult.errorCode == 0) {
        nativevalue_to_se(exResult, s.rval(), s.thisObject());
    } else {
        nativevalue_to_se(mgr->getRecordingDevice(), s.rval(), s.thisObject());
    }
    return true;
}
SE_BIND_FUNC(js_agora_AudioDeviceManagerBridge_getRecordingDevice)

// ===== ScreenCaptureSourceListBridge manual binding =======================

static bool js_agora_ScreenCaptureSourceListBridge_getSourceInfo(se::State &s) {
    const auto &args = s.args();
    auto *list = static_cast<ScreenCaptureSourceListBridge *>(s.nativeThisObject());
    if (list == nullptr || args.empty()) { s.rval().setInt32(-2); return true; }
    unsigned int index = static_cast<unsigned int>(args[0].toInt32());
    nativevalue_to_se(list->getSourceInfo(index), s.rval(), s.thisObject());
    return true;
}
SE_BIND_FUNC(js_agora_ScreenCaptureSourceListBridge_getSourceInfo)

// ===== ArrayBuffer-accepting bindings =======================================
// SWIG cannot auto-convert ArrayBuffer → (void*, size_t). Hand-write these.

static bool js_agora_RtcEngineBridge_sendStreamMessage(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 2) { SE_REPORT_ERROR("sendStreamMessage expects 2 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    auto streamId = args[0].toInt32();
    uint8_t *data = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[1], &data, &length)) {
        SE_REPORT_ERROR("sendStreamMessage: arg 1 must be ArrayBuffer"); return false;
    }
    s.rval().setInt32(bridge->sendStreamMessage(streamId, data, length));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendStreamMessage)

static bool js_agora_RtcEngineBridge_sendStreamMessageEx(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 3) { SE_REPORT_ERROR("sendStreamMessageEx expects 3 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    auto streamId = args[0].toInt32();
    uint8_t *data = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[1], &data, &length)) {
        SE_REPORT_ERROR("sendStreamMessageEx: arg 1 must be ArrayBuffer"); return false;
    }
    agora::rtc::RtcConnection connection;
    if (!sevalue_to_native(args[2], &connection, s.thisObject())) {
        SE_REPORT_ERROR("sendStreamMessageEx: failed to convert RtcConnection"); return false;
    }
    s.rval().setInt32(bridge->sendStreamMessageEx(streamId, data, length, connection));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendStreamMessageEx)

static bool js_agora_RtcEngineBridge_sendRdtMessage(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 3) { SE_REPORT_ERROR("sendRdtMessage expects 3 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    auto uid = static_cast<agora::rtc::uid_t>(args[0].toUint32());
    auto type = static_cast<agora::rtc::RdtStreamType>(args[1].toInt32());
    uint8_t *data = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[2], &data, &length)) {
        SE_REPORT_ERROR("sendRdtMessage: arg 2 must be ArrayBuffer"); return false;
    }
    s.rval().setInt32(bridge->sendRdtMessage(uid, type, data, length));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendRdtMessage)

static bool js_agora_RtcEngineBridge_sendRdtMessageEx(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 4) { SE_REPORT_ERROR("sendRdtMessageEx expects 4 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    auto uid = static_cast<agora::rtc::uid_t>(args[0].toUint32());
    auto type = static_cast<agora::rtc::RdtStreamType>(args[1].toInt32());
    uint8_t *data = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[2], &data, &length)) {
        SE_REPORT_ERROR("sendRdtMessageEx: arg 2 must be ArrayBuffer"); return false;
    }
    agora::rtc::RtcConnection connection;
    if (!sevalue_to_native(args[3], &connection, s.thisObject())) {
        SE_REPORT_ERROR("sendRdtMessageEx: failed to convert RtcConnection"); return false;
    }
    s.rval().setInt32(bridge->sendRdtMessageEx(uid, type, data, length, connection));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendRdtMessageEx)

static bool js_agora_RtcEngineBridge_sendMediaControlMessage(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 2) { SE_REPORT_ERROR("sendMediaControlMessage expects 2 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    auto uid = static_cast<agora::rtc::uid_t>(args[0].toUint32());
    uint8_t *data = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[1], &data, &length)) {
        SE_REPORT_ERROR("sendMediaControlMessage: arg 1 must be ArrayBuffer"); return false;
    }
    s.rval().setInt32(bridge->sendMediaControlMessage(uid, data, length));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendMediaControlMessage)

static bool js_agora_RtcEngineBridge_sendMediaControlMessageEx(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 3) { SE_REPORT_ERROR("sendMediaControlMessageEx expects 3 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    auto uid = static_cast<agora::rtc::uid_t>(args[0].toUint32());
    uint8_t *data = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[1], &data, &length)) {
        SE_REPORT_ERROR("sendMediaControlMessageEx: arg 1 must be ArrayBuffer"); return false;
    }
    agora::rtc::RtcConnection connection;
    if (!sevalue_to_native(args[2], &connection, s.thisObject())) {
        SE_REPORT_ERROR("sendMediaControlMessageEx: failed to convert RtcConnection"); return false;
    }
    s.rval().setInt32(bridge->sendMediaControlMessageEx(uid, data, length, connection));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendMediaControlMessageEx)

static bool js_agora_RtcEngineBridge_sendAudioMetadata(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 1) { SE_REPORT_ERROR("sendAudioMetadata expects 1 arg"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    uint8_t *metadata = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[0], &metadata, &length)) {
        SE_REPORT_ERROR("sendAudioMetadata: arg 0 must be ArrayBuffer"); return false;
    }
    s.rval().setInt32(bridge->sendAudioMetadata(metadata, length));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendAudioMetadata)

static bool js_agora_RtcEngineBridge_sendAudioMetadataEx(se::State &s) {
    ScopedCStringGuard _cstrGuard;
    const auto &args = s.args();
    if (args.size() < 2) { SE_REPORT_ERROR("sendAudioMetadataEx expects 2 args"); return false; }
    auto *bridge = getRtcEngineBridge(s);
    if (bridge == nullptr) { s.rval().setInt32(-7); return true; }
    agora::rtc::RtcConnection connection;
    if (!sevalue_to_native(args[0], &connection, s.thisObject())) {
        SE_REPORT_ERROR("sendAudioMetadataEx: failed to convert RtcConnection"); return false;
    }
    uint8_t *metadata = nullptr; size_t length = 0;
    if (!getArrayBufferOrTypedArray(args[1], &metadata, &length)) {
        SE_REPORT_ERROR("sendAudioMetadataEx: arg 1 must be ArrayBuffer"); return false;
    }
    s.rval().setInt32(bridge->sendAudioMetadataEx(connection, metadata, length));
    return true;
}
SE_BIND_FUNC(js_agora_RtcEngineBridge_sendAudioMetadataEx)

} // namespace

// ===== Registration ========================================================

bool register_agora_rtc_manual(se::Object *global) {
    // Merge manual bindings into auto-generated classes registered under jsb.agora

    // --- RtcEngineExBridge ---
    // The auto-generated code calls cls->install() which creates the V8 Function
    // from a cached template. A second cls->install() doesn't update the live
    // prototype. We must patch the prototype object directly.
    if (__jsb_RtcEngineExBridge_proto) {
        auto *proto = __jsb_RtcEngineExBridge_proto;
        proto->defineFunction("initialize", _SE(js_agora_RtcEngineBridge_initialize));
        proto->defineFunction("joinChannel", _SE(js_agora_RtcEngineBridge_joinChannel));
        proto->defineFunction("release", _SE(js_agora_RtcEngineBridge_release));
        proto->defineFunction("createMediaPlayer", _SE(js_agora_RtcEngineBridge_createMediaPlayer));
        proto->defineFunction("destroyMediaPlayer", _SE(js_agora_RtcEngineBridge_destroyMediaPlayer));
        proto->defineFunction("createMediaRecorder", _SE(js_agora_RtcEngineBridge_createMediaRecorder));
        proto->defineFunction("destroyMediaRecorder", _SE(js_agora_RtcEngineBridge_destroyMediaRecorder));
        proto->defineFunction("getScreenCaptureSources", _SE(js_agora_RtcEngineBridge_getScreenCaptureSources));
        proto->defineFunction("addVideoWatermark", _SE(js_agora_RtcEngineBridge_addVideoWatermark));
        proto->defineFunction("enableExtension", _SE(js_agora_RtcEngineBridge_enableExtension));
        proto->defineFunction("getExtensionProperty", _SE(js_agora_RtcEngineBridge_getExtensionProperty));
        proto->defineFunction("setExtensionProperty", _SE(js_agora_RtcEngineBridge_setExtensionProperty));
        proto->defineFunction("takeSnapshot", _SE(js_agora_RtcEngineBridge_takeSnapshot));
        proto->defineFunction("takeSnapshotEx", _SE(js_agora_RtcEngineBridge_takeSnapshotEx));
        proto->defineFunction("getAudioDeviceManager", _SE(js_agora_RtcEngineBridge_getAudioDeviceManager));
        proto->defineFunction("getVideoDeviceManager", _SE(js_agora_RtcEngineBridge_getVideoDeviceManager));
        proto->defineFunction("getMusicContentCenter", _SE(js_agora_RtcEngineBridge_getMusicContentCenter));
        proto->defineFunction("getMediaPlayerCacheManager", _SE(js_agora_RtcEngineBridge_getMediaPlayerCacheManager));
        proto->defineFunction("getLocalSpatialAudioEngine", _SE(js_agora_RtcEngineBridge_getLocalSpatialAudioEngine));
        proto->defineFunction("createVideoEffectObject", _SE(js_agora_RtcEngineBridge_createVideoEffectObject));
        proto->defineFunction("destroyVideoEffectObject", _SE(js_agora_RtcEngineBridge_destroyVideoEffectObject));
        proto->defineFunction("getH265Transcoder", _SE(js_agora_RtcEngineBridge_getH265Transcoder));
        proto->defineFunction("sendStreamMessage", _SE(js_agora_RtcEngineBridge_sendStreamMessage));
        proto->defineFunction("sendStreamMessageEx", _SE(js_agora_RtcEngineBridge_sendStreamMessageEx));
        proto->defineFunction("sendRdtMessage", _SE(js_agora_RtcEngineBridge_sendRdtMessage));
        proto->defineFunction("sendRdtMessageEx", _SE(js_agora_RtcEngineBridge_sendRdtMessageEx));
        proto->defineFunction("sendMediaControlMessage", _SE(js_agora_RtcEngineBridge_sendMediaControlMessage));
        proto->defineFunction("sendMediaControlMessageEx", _SE(js_agora_RtcEngineBridge_sendMediaControlMessageEx));
        proto->defineFunction("sendAudioMetadata", _SE(js_agora_RtcEngineBridge_sendAudioMetadata));
        proto->defineFunction("sendAudioMetadataEx", _SE(js_agora_RtcEngineBridge_sendAudioMetadataEx));
    }

    // --- MediaPlayerBridge ---
    if (__jsb_MediaPlayerBridge_proto) {
        auto *proto = __jsb_MediaPlayerBridge_proto;
        proto->defineFunction("registerPlayerSourceObserver", _SE(js_agora_MediaPlayerBridge_registerPlayerSourceObserver));
        proto->defineFunction("setPlayerOption", _SE(js_agora_MediaPlayerBridge_setPlayerOption));
    }

    // --- MusicContentCenterBridge ---
    if (__jsb_MusicContentCenterBridge_proto) {
        auto *proto = __jsb_MusicContentCenterBridge_proto;
        proto->defineFunction("unregisterEventHandler", _SE(js_agora_MusicContentCenterBridge_unregisterEventHandler));
        proto->defineFunction("createMusicPlayer", _SE(js_agora_MusicContentCenterBridge_createMusicPlayer));
        proto->defineFunction("destroyMusicPlayer", _SE(js_agora_MusicContentCenterBridge_destroyMusicPlayer));
    }

    // --- H265TranscoderBridge ---
    if (__jsb_H265TranscoderBridge_proto) {
        auto *proto = __jsb_H265TranscoderBridge_proto;
        proto->defineFunction("registerTranscoderObserver", _SE(js_agora_H265TranscoderBridge_registerTranscoderObserver));
    }

    // --- MediaRecorderBridge ---
    if (__jsb_MediaRecorderBridge_proto) {
        auto *proto = __jsb_MediaRecorderBridge_proto;
        proto->defineFunction("setMediaRecorderObserver", _SE(js_agora_MediaRecorderBridge_setMediaRecorderObserver));
    }

    // --- AudioDeviceCollectionBridge ---
    if (__jsb_AudioDeviceCollectionBridge_proto) {
        auto *proto = __jsb_AudioDeviceCollectionBridge_proto;
        proto->defineFunction("getDevice", _SE(js_agora_AudioDeviceCollectionBridge_getDevice));
        proto->defineFunction("getDefaultDevice", _SE(js_agora_AudioDeviceCollectionBridge_getDefaultDevice));
    }

    // --- AudioDeviceManagerBridge ---
    if (__jsb_AudioDeviceManagerBridge_proto) {
        auto *proto = __jsb_AudioDeviceManagerBridge_proto;
        proto->defineFunction("enumeratePlaybackDevices", _SE(js_agora_AudioDeviceManagerBridge_enumeratePlaybackDevices));
        proto->defineFunction("enumerateRecordingDevices", _SE(js_agora_AudioDeviceManagerBridge_enumerateRecordingDevices));
        proto->defineFunction("getPlaybackDevice", _SE(js_agora_AudioDeviceManagerBridge_getPlaybackDevice));
        proto->defineFunction("getRecordingDevice", _SE(js_agora_AudioDeviceManagerBridge_getRecordingDevice));
    }

    // --- ScreenCaptureSourceListBridge ---
    if (__jsb_ScreenCaptureSourceListBridge_proto) {
        auto *proto = __jsb_ScreenCaptureSourceListBridge_proto;
        proto->defineFunction("getSourceInfo", _SE(js_agora_ScreenCaptureSourceListBridge_getSourceInfo));
    }

    return true;
}
