#pragma once

#include "bindings/jswrapper/SeApi.h"
#include "bindings/manual/jsb_conversions.h"
#include "AgoraBase.h"
#include "AgoraMediaBase.h"
#include "AgoraMediaPlayerTypes.h"
#include "AgoraOptional.h"
#include "IAgoraRtcEngine.h"
#include "IAgoraSpatialAudio.h"
#include "IAgoraMusicContentCenter.h"

// Forward declarations — sevalue_to_native implementations are
// generated by scripts/generate-sevalue-to-native.js.
// Re-run: npm run genbindings:sevalue

// AUTO-GENERATED DECLARATIONS START

// ─────────────────────────────────────────────────────────────────────────────
// This file is AUTO-GENERATED by scripts/generate-sevalue-to-native.js.
//
// To prevent a specific function from being overwritten on regeneration, add
// the line below immediately above it:
//
//   // do not gen code cover it
//   bool sevalue_to_native(const se::Value &from, YourStruct *to, se::Object *ctx) { ... }
//
// Custom code between // USER CODE BLOCK START and // USER CODE BLOCK END is preserved.
// ─────────────────────────────────────────────────────────────────────────────
bool sevalue_to_native(const se::Value &from, agora::UserInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDimensions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SenderOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedAudioFrameAdvancedSettings *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedAudioFrameInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioPcmDataInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoSubscriptionOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncodedVideoFrameInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvanceOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::CodecCapLevels *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::CodecCapInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FocalLengthInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoEncoderConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DataStreamConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastStreamConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::Rectangle *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkRatio *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkTimestamp *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkLiteral *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkBuffer *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::WatermarkConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::PathStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MultipathStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ClientRoleOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoTrackInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioVolumeInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DeviceInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LiveStreamAdvancedFeature *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TranscodingUser *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LiveTranscoding *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::TranscodingVideoStream *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalTranscoderConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MixedAudioStream *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAudioMixerConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeOneWayResult *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LastmileProbeResult *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoCanvas *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::BeautyOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FaceShapeAreaOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FaceShapeBeautyOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::FilterEffectOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LowlightEnhanceOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoDenoiserOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ColorEnhanceOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VirtualBackgroundSource *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SegmentationProperty *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioTrackConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenAudioParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioRecordingConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioEncodedFrameObserverConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaRelayConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::UplinkNetworkInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DownlinkNetworkInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EncryptionConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::EchoTestConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::UserInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::VideoRenderingTracingInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LogUploadServerInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvancedConfigInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LocalAccessPointConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RecorderStreamInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::SpatialAudioParams *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::VideoLayout *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionContext *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AudioParameters *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVideoStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::InjectStreamConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::PublisherConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SIZE *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ThumbImageBuffer *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::LeaveChannelOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcEngineContext *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DirectCdnStreamingStats *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ExtensionInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcConnection *to, se::Object *ctx);
// USER CODE BLOCK START
bool sevalue_to_native(const se::Value &from, agora::media::SnapshotConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RtcImage *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ChannelMediaOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::CameraCapturerConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SimulcastConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ScreenCaptureConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::DirectCdnStreamingMediaOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AgoraRhythmPlayerConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::media::ContentInspectConfig *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::AdvancedAudioOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::ImageTrackOptions *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::RemoteVoicePositionInfo *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::SpatialAudioZone *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::media::MediaRecorderConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::rtc::MusicContentCenterConfiguration *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::util::CopyableAutoPtr<agora::util::IString> *to, se::Object *ctx);
bool sevalue_to_native(const se::Value &from, agora::commons::LogConfig *to, se::Object *ctx);


// Array type stubs for Optional<T> compatibility
template<size_t N>
bool sevalue_to_native(const se::Value &from, unsigned char (*to)[N], se::Object *ctx) { return true; }
template<size_t N>
bool sevalue_to_native(const se::Value &from, char (*to)[N], se::Object *ctx) { return true; }

namespace agora {
// Generic converter for Optional<T>
template<typename T>
bool sevalue_to_native(const se::Value &from, Optional<T> *to, se::Object *ctx) {
    if (from.isNullOrUndefined()) {
        *to = nullopt;
        return true;
    }
    T val{};
    if (!::sevalue_to_native(from, &val, ctx)) return false;
    *to = std::move(val);
    return true;
}
}
// USER CODE BLOCK END
// AUTO-GENERATED DECLARATIONS END
